server:
  port: 80


spring:
#redis
  redis:
    host: localhost
    port: 6379
    timeout: 1000

#放行静态资源
  mvc:
    static-path-pattern: /static/**

#禁止页面缓存
  thymeleaf:
    cache: false

feign:
  hystrix:
    enabled: true

eureka:
   client:
     register-with-eureka: false
     service-url:
       defaultZone: http://eureka7001.com:7001/eureka

